version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: twoflocal_postgres
    environment:
      POSTGRES_DB: twoflocal_db
      POSTGRES_USER: twoflocal_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-twoflocal_pass} # Default if .env not present
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
