name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ios-tests:
    name: iOS E2E Tests
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
          
      - name: Install dependencies
        working-directory: app
        run: npm ci
        
      - name: Install Detox CLI
        run: npm install -g detox-cli
        
      - name: Install Applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
          
      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('app/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
            
      - name: Install Pods
        working-directory: app/ios
        run: pod install
        
      - name: Build iOS app for testing
        working-directory: app
        run: detox build --configuration ios.debug
        
      - name: Run E2E tests on iOS
        working-directory: app
        run: detox test --configuration ios.debug --cleanup
        
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ios-test-artifacts
          path: |
            app/artifacts
            
  android-tests:
    name: Android E2E Tests
    runs-on: macos-latest # Using macOS for better Android emulator performance
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
          
      - name: Install dependencies
        working-directory: app
        run: npm ci
        
      - name: Install Detox CLI
        run: npm install -g detox-cli
        
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('app/android/gradle/wrapper/gradle-wrapper.properties', 'app/android/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Build Android app for testing
        working-directory: app
        run: detox build --configuration android.debug
        
      - name: Create and start Android emulator
        working-directory: app
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_4_API_30 -d "pixel_4" -k "system-images;android-30;google_apis;x86_64"
          $ANDROID_HOME/emulator/emulator -avd Pixel_4_API_30 -no-audio -no-boot-anim -no-window -gpu swiftshader_indirect &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          
      - name: Run E2E tests on Android
        working-directory: app
        run: detox test --configuration android.debug --cleanup
        
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-test-artifacts
          path: |
            app/artifacts