apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-data
  namespace: 2flocal-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard