apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: 2flocal-staging
data:
  NODE_ENV: "staging"
  PORT: "3000"
  API_URL: "https://api-staging.2flocal.com"
  LOG_LEVEL: "debug"
  FEATURE_FLAG_ENHANCED_SECURITY: "true"
  FEATURE_FLAG_BETA_FEATURES: "true"