apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: 2flocal-staging
type: Opaque
data:
  # These are base64 encoded values (in a real scenario, use Sealed Secrets or external-secrets)
  # Example: echo -n "your-secret" | base64
  JWT_SECRET: c3RhZ2luZy1qd3Qtc2VjcmV0LWV4YW1wbGU=  # staging-jwt-secret-example
  ENCRYPTION_KEY: c3RhZ2luZy1lbmNyeXB0aW9uLWtleS1leGFtcGxl  # staging-encryption-key-example
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBzdGFnaW5nLWRiLmV4YW1wbGUuY29tOjU0MzIvMmZsb2NhbA==  # postgres://username:password@staging-db.example.com:5432/2flocal