default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "TwoFLocal.xcodeproj")
    build_app(workspace: "TwoFLocal.xcworkspace", scheme: "TwoFLocal")
    upload_to_testflight
  end

  desc "Build and upload to App Store"
  lane :release do
    increment_build_number(xcodeproj: "TwoFLocal.xcodeproj")
    build_app(workspace: "TwoFLocal.xcworkspace", scheme: "TwoFLocal")
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
  end
end