apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: 2flocal-staging
  labels:
    app: db-backup
    environment: staging
spec:
  schedule: "0 1 * * *"  # Run daily at 1 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: db-backup
            environment: staging
        spec:
          restartPolicy: OnFailure
          containers:
          - name: db-backup
            image: postgres:14
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h postgres -U $POSTGRES_USER -d 2flocal -F c -f /backup/2flocal-staging-$(date +%Y%m%d-%H%M%S).dump
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: postgres-backup-data