apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: 2flocal-staging
  labels:
    app: db-migration
    environment: staging
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: db-migration
        environment: staging
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-migration
        image: 2flocal/backend:staging
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: NODE_ENV
          value: staging
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
      backoffLimit: 3