apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: 2flocal-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard