apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: 2flocal-staging
type: Opaque
data:
  # These are base64 encoded values (in a real scenario, use Sealed Secrets or external-secrets)
  # Example: echo -n "your-secret" | base64
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: c3RhZ2luZy1wYXNzd29yZC1leGFtcGxl  # staging-password-example