apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: 2flocal-staging
  labels:
    app: postgres
    environment: staging
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP